[font]
size = 12.0

[font.bold]
family = "Comic Mono"
style = "Bold"

[font.bold_italic]
family = "Comic Mono"
style = "Bold Italic"

[font.italic]
family = "Comic Mono"
style = "Italic"

[font.normal]
family = "Comic Mono"
style = "Normal"

[scrolling]
history = 50000

[window]
opacity = 0.65
padding = { x = 12, y = 12 }
decorations = "none"

[cursor]
style = { shape = "Beam", blinking = "On" }

[colors.primary]
background = "#121214"
foreground = "#eeeeee"

# Dracula+ Theme
# https://github.com/mbadolato/iTerm2-Color-Schemes/blob/9526f1299da83c1cc83cd0236bf7d24e65731a79/alacritty/Dracula%2B.toml#L1
[colors.bright]
black = "#545454"
blue = "#d6acff"
cyan = "#a4ffff"
green = "#69ff94"
magenta = "#ff92df"
red = "#ff6e6e"
white = "#f8f8f2"
yellow = "#ffcb6b"

[colors.cursor]
cursor = "#eceff4"
text = "#282828"

[colors.normal]
black = "#21222c"
blue = "#82aaff"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#c792ea"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#ffcb6b"

[colors.selection]
background = "#f8f8f2"
text = "#545454"
