[font]
size = 12.0

[font.bold]
family = "Comic Mono"
style = "Bold"

[font.bold_italic]
family = "Comic Mono"
style = "Bold Italic"

[font.italic]
family = "Comic Mono"
style = "Italic"

[font.normal]
family = "Comic Mono"
style = "Normal"

[scrolling]
history = 50000

[window]
opacity = 0.65
padding = { x = 12, y = 12 }
decorations = "none"

[cursor]
style = { shape = "Beam", blinking = "On" }

[colors.primary]
background = "#121214"
foreground = "#eeeeee"

# SpaceGray Eighties Theme
# https://github.com/mbadolato/iTerm2-Color-Schemes/blob/9526f1299da83c1cc83cd0236bf7d24e65731a79/alacritty/SpaceGray%20Eighties.toml
[colors.bright]
black = '#555555'
blue = '#4d84d1'
cyan = '#83e9e4'
green = '#93d493'
magenta = '#ff55ff'
red = '#ff6973'
white = '#ffffff'
yellow = '#ffd256'

[colors.cursor]
cursor = '#bbbbbb'
text = '#ffffff'

[colors.normal]
black = '#15171c'
blue = '#5486c0'
cyan = '#57c2c1'
green = '#81a764'
magenta = '#bf83c1'
red = '#ec5f67'
white = '#efece7'
yellow = '#fec254'

[colors.selection]
background = '#272e35'
text = '#ffffff'